// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/category/Get/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "category"
                ],
                "summary": "Получить категорию",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор категории",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/category/create": {
            "post": {
                "description": "Добавляет категорию",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "category"
                ],
                "summary": "Добавить категорию",
                "parameters": [
                    {
                        "description": "Тело запроса",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/category.CreateCategory"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/category/delete/{id}": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "category"
                ],
                "summary": "Обновить категорию",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор категории",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/category/getall": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "category"
                ],
                "summary": "Получить список категорий",
                "responses": {}
            }
        },
        "/api/v1/category/update": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "category"
                ],
                "summary": "Обновить категорию",
                "parameters": [
                    {
                        "description": "Тело запроса",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/category.UpdateCategory"
                        }
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "category.CreateCategory": {
            "type": "object",
            "properties": {
                "childs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "parentId": {
                    "type": "string"
                }
            }
        },
        "category.UpdateCategory": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "parentId": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
